# Site settings.
title: Polish BSD User Group
url: "https://bsd-pl.org"
logo: "bsdpl-logo.png"

# Build settings.
theme: jekyll-theme-minimal

# Social media.
facebook_url: https://www.facebook.com/pg/The-Polish-BSD-User-Group-2104511872897332
twitter_url: https://twitter.com/BSD_PL
