# Site settings.
title: Polish BSD User Group
url: "https://bsd-pl.org"
logo: "bsdpl-logo.png"

# Build settings.
theme: jekyll-theme-minimal

# Social media.
mail_url: mailto:meetup@bsd-pl.org
facebook_url: https://www.facebook.com/pg/The-Polish-BSD-User-Group-2104511872897332
twitter_url: https://twitter.com/BSD_PL
youtube_url: https://www.youtube.com/channel/UCWvDQaEHSULuCIVOOM66nYA
mailchanp_url: https://bsd-pl.us18.list-manage.com/subscribe?u=9da833a0b60761893d91b1601&id=c8442bda1e
